name: Build and publish a community Backstage image

on:
  push:
    branches: [community-backstage-image]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: fetch branch community-backstage-image
        run: git fetch origin community-backstage-image

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: type checking and declarations
        run: yarn run tsc --incremental false

      - name: build all packages - TS to JS
        run: yarn run build

      - name: Set image version
        run: |
          echo "IMAGE_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
          echo ${{ env.IMAGE_VERSION }} > IMAGE_VERSION

      - name: docker build backend
        run: yarn workspace example-backend build-image --file $PWD/contrib/docker/kubernetes-example-backend/Dockerfile

      - name: docker tag backend
        run: docker tag example-backend:latest roadiehq/community-backstage-image:${{ env.IMAGE_VERSION }}

      - name: docker push backend
        run: docker push roadiehq/community-backstage-image:${{ env.IMAGE_VERSION }}

      - name: docker update latest tags
        run: |
          docker tag example-backend:latest roadiehq/community-backstage-image:latest
          docker push roadiehq/community-backstage-image:latest
